version: "3.7"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
  ext-postgres:
